### ISSUE TITLE
Error, can u help me out?

### ISSUE THREAD

**Issue by mv-stns** [octfx/FreelanceCockpitDocker#1]
<img width="1767" alt="Bildschirmfoto 2020-07-02 um 21 37 46" src="https://user-images.githubusercontent.com/21103251/86402532-47030b00-bcac-11ea-8717-41700f67ca54.png">

**Comment by mv-stns** [comment]
<img width="659" alt="Bildschirmfoto 2020-07-02 um 21 38 27" src="https://user-images.githubusercontent.com/21103251/86402593-61d57f80-bcac-11ea-8094-6c4d8a728e1a.png">
Am i missing something?

**Comment by octfx** [comment]
Does the `FC_application` folder contain all app files like `application, sparks, vendor...`?

**Comment by mv-stns** [comment]
Yes it does

**Comment by octfx** [comment]
I'll have a look!

**Comment by octfx** [comment]
Whats the value of `DB_HOST` in your environment file?  
It has to be `db` (the name of the database container from your docker-compose.yml)

**Comment by mv-stns** [comment]
> Whats the value of `DB_HOST` in your environment file?
> It has to be `db` (the name of the database container from your docker-compose.yml)

Which environment file?

**Comment by octfx** [comment]
You need to copy the `.env.example` file from the `FC_application` folder to the directory where the compose file is and rename it to `environment` (second line under volumes)
There the `DB_HOST` key has to have a value of `db`

**Comment by mv-stns** [comment]
Oh men.. Okay. Docker is very new for me. Can't follow up. Thanks anyway. I can't find the `.env.example` file. Gtg study more docker.

**Comment by octfx** [comment]
I'll try to update the readme tomorrow with a installation guide. :)

**Comment by mv-stns** [comment]
Thanks a lot! I appreciate your help!

**Comment by mv-stns** [comment]
Ach ich seh gerade du sprichst Deutsch. Vielen dank für deine Hilfe!

**Comment by octfx** [comment]
Kein Problem!   
Ich habe die `docker-compose.yml` und die readme geupdatet. Kannst du es nochmal versuchen?

**Comment by mv-stns** [comment]
Klar, ich meld mich gleich nochmal!

**Comment by mv-stns** [comment]
<img width="1038" alt="Bildschirmfoto 2020-07-03 um 14 02 09" src="https://user-images.githubusercontent.com/21103251/86467527-d1dc1800-bd35-11ea-878b-205648aadad3.png">
So, nun haben wir es fast, fehlt nur noch die extension. Der lässt mich nämlich nicht mehr weiter klicken um die installation zu beenden

**Comment by octfx** [comment]
Hast du die neueste Version von FC? Mcrypt ist eigentlich nicht mehr nutzbar und wurde in PHP 7.2 komplett entfernt.
Im Installationsprozess von v4.0.2 wird Mcrypt nicht mehr aufgeführt.

**Comment by mv-stns** [comment]
> Hast du die neueste Version von FC? Mcrypt ist eigentlich nicht mehr nutzbar und wurde in PHP 7.2 komplett entfernt.
> Im Installationsprozess von v4.0.2 wird Mcrypt nicht mehr aufgeführt.

Das erklärt nun einiges, ne ich hab eine veraltete version davon.

**Comment by octfx** [comment]
Ich denke mal mit der neuesten Version sollte nun alles klappen.
Falls nicht kannst du dieses Issue ja wieder öffnen, viel Erfolg! 🎉
